// <auto-generated />
using System;
using CleanOpsAi.Modules.Scoring.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CleanOpsAi.Modules.Scoring.Infrastructure.Migrations
{
    [DbContext(typeof(ScoringDbContext))]
    [Migration("20260507160319_AddScoringRetrainRunLogs")]
    partial class AddScoringRetrainRunLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scoring")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringAnnotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AnnotationFormat")
                        .HasColumnType("integer")
                        .HasColumnName("annotation_format");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LabelsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("labels_json")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("ReviewerNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reviewer_note");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_scoring_annotations");

                    b.HasIndex("CandidateId")
                        .IsUnique()
                        .HasDatabaseName("ix_scoring_annotations_candidate_id");

                    b.HasIndex("Created")
                        .HasDatabaseName("ix_scoring_annotations_created");

                    b.ToTable("scoring_annotations", "scoring");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringAnnotationCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<int>("CandidateStatus")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_status");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("EnvironmentKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("environment_key");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("MetadataBlobKey")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("metadata_blob_key");

                    b.Property<string>("OriginalVerdict")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("original_verdict");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("request_id");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_id");

                    b.Property<string>("ReviewedVerdict")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reviewed_verdict");

                    b.Property<string>("SnapshotBlobKey")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("snapshot_blob_key");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_type");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<string>("VisualizationBlobUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("visualization_blob_url");

                    b.HasKey("Id")
                        .HasName("pk_scoring_annotation_candidates");

                    b.HasIndex("AssignedToUserId")
                        .HasDatabaseName("ix_scoring_annotation_candidates_assigned_to_user_id");

                    b.HasIndex("CandidateStatus")
                        .HasDatabaseName("ix_scoring_annotation_candidates_candidate_status");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_scoring_annotation_candidates_created_at_utc");

                    b.HasIndex("EnvironmentKey")
                        .HasDatabaseName("ix_scoring_annotation_candidates_environment_key");

                    b.HasIndex("ResultId")
                        .IsUnique()
                        .HasDatabaseName("ix_scoring_annotation_candidates_result_id");

                    b.ToTable("scoring_annotation_candidates", "scoring");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("EnvironmentKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("environment_key");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("request_id");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_scoring_jobs");

                    b.HasIndex("Created")
                        .HasDatabaseName("ix_scoring_jobs_created");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_scoring_jobs_request_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_scoring_jobs_status");

                    b.ToTable("scoring_jobs", "scoring");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringJobResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<double>("QualityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("quality_score");

                    b.Property<Guid>("ScoringJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("scoring_job_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source_type");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("verdict");

                    b.HasKey("Id")
                        .HasName("pk_scoring_job_results");

                    b.HasIndex("Created")
                        .HasDatabaseName("ix_scoring_job_results_created");

                    b.HasIndex("ScoringJobId")
                        .HasDatabaseName("ix_scoring_job_results_scoring_job_id");

                    b.ToTable("scoring_job_results", "scoring");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringRetrainBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AnnotatedSampleCount")
                        .HasColumnType("integer")
                        .HasColumnName("annotated_sample_count");

                    b.Property<int>("ApprovedAnnotationCount")
                        .HasColumnType("integer")
                        .HasColumnName("approved_annotation_count");

                    b.Property<double?>("BaselineMetric")
                        .HasColumnType("double precision")
                        .HasColumnName("baseline_metric");

                    b.Property<int>("CalibrationSampleCount")
                        .HasColumnType("integer")
                        .HasColumnName("calibration_sample_count");

                    b.Property<double?>("CandidateMetric")
                        .HasColumnType("double precision")
                        .HasColumnName("candidate_metric");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("MetricKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("metric_key");

                    b.Property<double?>("MinimumImprovement")
                        .HasColumnType("double precision")
                        .HasColumnName("minimum_improvement");

                    b.Property<bool>("Promoted")
                        .HasColumnType("boolean")
                        .HasColumnName("promoted");

                    b.Property<string>("PromotionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("promotion_reason");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc");

                    b.Property<int>("ReviewedSampleCount")
                        .HasColumnType("integer")
                        .HasColumnName("reviewed_sample_count");

                    b.Property<DateTime>("SourceWindowFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_window_from_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_scoring_retrain_batches");

                    b.HasIndex("Created")
                        .HasDatabaseName("ix_scoring_retrain_batches_created");

                    b.HasIndex("RequestedAtUtc")
                        .HasDatabaseName("ix_scoring_retrain_batches_requested_at_utc");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_scoring_retrain_batches_status");

                    b.ToTable("scoring_retrain_batches", "scoring");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringRetrainRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer")
                        .HasColumnName("exit_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Logs")
                        .HasColumnType("text")
                        .HasColumnName("logs");

                    b.Property<string>("Message")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("message");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mode");

                    b.Property<Guid>("ScoringRetrainBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("scoring_retrain_batch_id");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_scoring_retrain_runs");

                    b.HasIndex("ScoringRetrainBatchId")
                        .HasDatabaseName("ix_scoring_retrain_runs_scoring_retrain_batch_id");

                    b.HasIndex("StartedAtUtc")
                        .HasDatabaseName("ix_scoring_retrain_runs_started_at_utc");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_scoring_retrain_runs_status");

                    b.ToTable("scoring_retrain_runs", "scoring");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringAnnotation", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringAnnotationCandidate", "Candidate")
                        .WithOne("Annotation")
                        .HasForeignKey("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringAnnotation", "CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scoring_annotations_scoring_annotation_candidates_candidate");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringAnnotationCandidate", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringJobResult", "Result")
                        .WithMany("AnnotationCandidates")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scoring_annotation_candidates_scoring_job_results_result_id");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringJobResult", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringJob", "ScoringJob")
                        .WithMany("Results")
                        .HasForeignKey("ScoringJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scoring_job_results_scoring_jobs_scoring_job_id");

                    b.Navigation("ScoringJob");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringRetrainRun", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringRetrainBatch", "Batch")
                        .WithMany("Runs")
                        .HasForeignKey("ScoringRetrainBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scoring_retrain_runs_scoring_retrain_batches_scoring_retrai");

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringAnnotationCandidate", b =>
                {
                    b.Navigation("Annotation");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringJob", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringJobResult", b =>
                {
                    b.Navigation("AnnotationCandidates");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringRetrainBatch", b =>
                {
                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
