// <auto-generated />
using System;
using CleanOpsAi.Modules.Scoring.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CleanOpsAi.Modules.Scoring.Infrastructure.Migrations
{
    [DbContext(typeof(ScoringDbContext))]
    [Migration("20260411121209_InitialScoring")]
    partial class InitialScoring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scoring")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("EnvironmentKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("environment_key");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("request_id");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_scoring_jobs");

                    b.HasIndex("Created")
                        .HasDatabaseName("ix_scoring_jobs_created");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_scoring_jobs_request_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_scoring_jobs_status");

                    b.ToTable("scoring_jobs", "scoring");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringJobResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<double>("QualityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("quality_score");

                    b.Property<Guid>("ScoringJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("scoring_job_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source_type");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("verdict");

                    b.HasKey("Id")
                        .HasName("pk_scoring_job_results");

                    b.HasIndex("Created")
                        .HasDatabaseName("ix_scoring_job_results_created");

                    b.HasIndex("ScoringJobId")
                        .HasDatabaseName("ix_scoring_job_results_scoring_job_id");

                    b.ToTable("scoring_job_results", "scoring");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringJobResult", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringJob", "ScoringJob")
                        .WithMany("Results")
                        .HasForeignKey("ScoringJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scoring_job_results_scoring_jobs_scoring_job_id");

                    b.Navigation("ScoringJob");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Scoring.Domain.Entities.ScoringJob", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
