// <auto-generated />
using System;
using CleanOpsAi.Modules.Workforce.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CleanOpsAi.Modules.Workforce.Infrastructure.Migrations
{
    [DbContext(typeof(WorkforceDbContext))]
    [Migration("20260320102625_TableWorkareaSupervisorInit")]
    partial class TableWorkareaSupervisorInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workforce")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CleanOpsAi.Modules.Workforce.Domain.Entities.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("IssuingOrganization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuing_organization");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_certifications");

                    b.ToTable("certifications", "workforce");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Workforce.Domain.Entities.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_equipments");

                    b.ToTable("equipments", "workforce");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Workforce.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_skill");

                    b.ToTable("skill", "workforce");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Workforce.Domain.Entities.WorkAreaSupervisor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("WorkAreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_area_id");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_workarea_supervisors");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_workarea_supervisors_user_id");

                    b.HasIndex("WorkAreaId")
                        .HasDatabaseName("ix_workarea_supervisors_work_area_id");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_workarea_supervisors_worker_id");

                    b.HasIndex("WorkAreaId", "WorkerId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_workarea_supervisors_work_area_id_worker_id_user_id")
                        .HasFilter("\"work_area_id\" IS NOT NULL AND \"worker_id\" IS NOT NULL");

                    b.ToTable("workarea_supervisors", "workforce");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Workforce.Domain.Entities.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayAddress")
                        .HasColumnType("text")
                        .HasColumnName("display_address");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_workers");

                    b.ToTable("workers", "workforce");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Workforce.Domain.Entities.WorkerCertification", b =>
                {
                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.Property<Guid>("CertificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("certification_id");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_date");

                    b.HasKey("WorkerId", "CertificationId")
                        .HasName("pk_worker_certifications");

                    b.HasIndex("CertificationId")
                        .HasDatabaseName("ix_worker_certifications_certification_id");

                    b.ToTable("worker_certifications", "workforce");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Workforce.Domain.Entities.WorkerGps", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_worker_gps");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_worker_gps_worker_id");

                    b.ToTable("worker_gps", "workforce");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Workforce.Domain.Entities.WorkerSkill", b =>
                {
                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("integer")
                        .HasColumnName("skill_level");

                    b.HasKey("WorkerId", "SkillId")
                        .HasName("pk_worker_skills");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_worker_skills_skill_id");

                    b.ToTable("worker_skills", "workforce");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Workforce.Domain.Entities.WorkAreaSupervisor", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.Workforce.Domain.Entities.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workarea_supervisors_workers_worker_id");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Workforce.Domain.Entities.WorkerCertification", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.Workforce.Domain.Entities.Certification", "Certification")
                        .WithMany("WorkerCertifications")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_worker_certifications_certifications_certification_id");

                    b.HasOne("CleanOpsAi.Modules.Workforce.Domain.Entities.Worker", "Worker")
                        .WithMany("WorkerCertifications")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_worker_certifications_workers_worker_id");

                    b.Navigation("Certification");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Workforce.Domain.Entities.WorkerGps", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.Workforce.Domain.Entities.Worker", "Worker")
                        .WithMany("WorkerGps")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_worker_gps_workers_worker_id");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Workforce.Domain.Entities.WorkerSkill", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.Workforce.Domain.Entities.Skill", "Skill")
                        .WithMany("WorkerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_worker_skills_skill_skill_id");

                    b.HasOne("CleanOpsAi.Modules.Workforce.Domain.Entities.Worker", "Worker")
                        .WithMany("WorkerSkills")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_worker_skills_workers_worker_id");

                    b.Navigation("Skill");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Workforce.Domain.Entities.Certification", b =>
                {
                    b.Navigation("WorkerCertifications");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Workforce.Domain.Entities.Skill", b =>
                {
                    b.Navigation("WorkerSkills");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.Workforce.Domain.Entities.Worker", b =>
                {
                    b.Navigation("WorkerCertifications");

                    b.Navigation("WorkerGps");

                    b.Navigation("WorkerSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
