version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"   
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  cleanopsai-api:
    container_name: cleanopsai-api
    build:
      context: ./src
      dockerfile: Api/CleanOpsAi.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  rabbitmq_data:

    