version: '3.8'

services:
  cleanopsai-api:
    container_name: cleanopsai-api
    build:
      context: ./src
      dockerfile: Api/CleanOpsAi.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
