// <auto-generated />
using System;
using CleanOpsAi.Modules.TaskOperations.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CleanOpsAi.Modules.TaskOperations.Infrastructure.Migrations
{
    [DbContext(typeof(TaskOperationsDbContext))]
    [Migration("20260416011036_InitEquipmentRequestItem")]
    partial class InitEquipmentRequestItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("task_operations")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.AdHocRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("RequestDateFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("request_date_from");

                    b.Property<DateTime?>("RequestDateTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("request_date_to");

                    b.Property<int>("RequestType")
                        .HasColumnType("integer")
                        .HasColumnName("request_type");

                    b.Property<Guid>("RequestedByWorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_worker_id");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("TaskAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_assignment_id");

                    b.HasKey("Id")
                        .HasName("pk_adhoc_requests");

                    b.HasIndex("TaskAssignmentId")
                        .HasDatabaseName("ix_adhoc_requests_task_assignment_id");

                    b.ToTable("adhoc_requests", "task_operations");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.ComplianceCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Feedback")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("feedback");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskStepExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_step_execution_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_compliance_checks");

                    b.HasIndex("TaskStepExecutionId")
                        .HasDatabaseName("ix_compliance_checks_task_step_execution_id");

                    b.ToTable("compliance_checks", "task_operations");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.EmergencyLeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("audio_url");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LeaveDateFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("leave_date_from");

                    b.Property<DateTime>("LeaveDateTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("leave_date_to");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("TaskAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_assignment_id");

                    b.Property<string>("Transcription")
                        .HasColumnType("text")
                        .HasColumnName("transcription");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_emergency_leave_requests");

                    b.HasIndex("TaskAssignmentId")
                        .HasDatabaseName("ix_emergency_leave_requests_task_assignment_id");

                    b.ToTable("emergency_leave_requests", "task_operations");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.EquipmentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_assignment_id");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_equipment_requests");

                    b.HasIndex("TaskAssignmentId")
                        .HasDatabaseName("ix_equipment_requests_task_assignment_id");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_equipment_requests_worker_id");

                    b.ToTable("equipment_requests", "task_operations");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.EquipmentRequestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<Guid>("EquipmentRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_request_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_equipment_request_items");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_equipment_request_items_equipment_id");

                    b.HasIndex("EquipmentRequestId")
                        .HasDatabaseName("ix_equipment_request_items_equipment_request_id");

                    b.HasIndex("EquipmentRequestId", "EquipmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_equipment_request_items_equipment_request_id_equipment_id");

                    b.ToTable("equipment_request_items", "task_operations");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.IssueReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("ReportedByWorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by_worker_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_assignment_id");

                    b.HasKey("Id")
                        .HasName("pk_issue_reports");

                    b.HasIndex("ReportedByWorkerId")
                        .HasDatabaseName("ix_issue_reports_reported_by_worker_id");

                    b.HasIndex("TaskAssignmentId")
                        .HasDatabaseName("ix_issue_reports_task_assignment_id");

                    b.ToTable("issue_reports", "task_operations");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<string>("AssigneeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("assignee_name");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayLocation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("display_location");

                    b.Property<bool>("IsAdhocTask")
                        .HasColumnType("boolean")
                        .HasColumnName("is_adhoc_task");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("NameAdhocTask")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_adhoc_task");

                    b.Property<Guid>("OriginalAssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_assignee_id");

                    b.Property<string>("OriginalAssigneeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_assignee_name");

                    b.Property<DateTime>("ScheduledEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_end_at");

                    b.Property<DateTime>("ScheduledStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_start_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_schedule_id");

                    b.Property<Guid>("WorkAreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_area_id");

                    b.HasKey("Id")
                        .HasName("pk_task_assignments");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_task_assignments_assignee_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_task_assignments_status");

                    b.HasIndex("TaskScheduleId")
                        .HasDatabaseName("ix_task_assignments_task_schedule_id");

                    b.HasIndex("TaskScheduleId", "ScheduledStartAt")
                        .IsUnique()
                        .HasDatabaseName("ix_task_assignments_task_schedule_id_scheduled_start_at")
                        .HasFilter("is_deleted = false");

                    b.ToTable("task_assignments", "task_operations");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_assignment_id");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_task_history");

                    b.HasIndex("TaskAssignmentId")
                        .HasDatabaseName("ix_task_history_task_assignment_id");

                    b.ToTable("task_history", "task_operations");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskStepExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ConfigSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_snapshot");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("ResultData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_data");

                    b.Property<Guid>("SopStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("sop_step_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("step_order");

                    b.Property<Guid>("TaskAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_assignment_id");

                    b.HasKey("Id")
                        .HasName("pk_task_step_executions");

                    b.HasIndex("TaskAssignmentId")
                        .HasDatabaseName("ix_task_step_executions_task_assignment_id");

                    b.ToTable("task_step_executions", "task_operations");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskStepExecutionImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("ImageType")
                        .HasColumnType("integer")
                        .HasColumnName("image_type");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("TaskStepExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_step_execution_id");

                    b.HasKey("Id")
                        .HasName("pk_task_step_execution_images");

                    b.HasIndex("TaskStepExecutionId")
                        .HasDatabaseName("ix_task_step_execution_images_task_step_execution_id");

                    b.ToTable("task_step_execution_images", "task_operations");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskSwapRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<string>("RequesterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("requester_name");

                    b.Property<string>("RequesterNote")
                        .HasColumnType("text")
                        .HasColumnName("requester_note");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text")
                        .HasColumnName("review_note");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("ReviewerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reviewer_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetTaskAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_task_assignment_id");

                    b.Property<Guid>("TargetWorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_worker_id");

                    b.Property<string>("TargetWorkerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_worker_name");

                    b.Property<Guid>("TaskAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_assignment_id");

                    b.HasKey("Id")
                        .HasName("pk_task_swap_requests");

                    b.HasIndex("TargetTaskAssignmentId")
                        .HasDatabaseName("ix_task_swap_requests_target_task_assignment_id");

                    b.HasIndex("TaskAssignmentId")
                        .HasDatabaseName("ix_task_swap_requests_task_assignment_id");

                    b.ToTable("task_swap_requests", "task_operations");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.AdHocRequest", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskAssignment", "TaskAssignment")
                        .WithMany("AdHocRequests")
                        .HasForeignKey("TaskAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_adhoc_requests_task_assignments_task_assignment_id");

                    b.Navigation("TaskAssignment");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.ComplianceCheck", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskStepExecution", "TaskStepExecution")
                        .WithMany("ComplianceChecks")
                        .HasForeignKey("TaskStepExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_compliance_checks_task_step_executions_task_step_execution_");

                    b.Navigation("TaskStepExecution");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.EmergencyLeaveRequest", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskAssignment", "TaskAssignment")
                        .WithMany("EmergencyLeaveRequests")
                        .HasForeignKey("TaskAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_emergency_leave_requests_task_assignments_task_assignment_id");

                    b.Navigation("TaskAssignment");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.EquipmentRequest", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskAssignment", null)
                        .WithMany("EquipmentRequests")
                        .HasForeignKey("TaskAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_requests_task_assignments_task_assignment_id");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.EquipmentRequestItem", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.TaskOperations.Domain.Entities.EquipmentRequest", "EquipmentRequest")
                        .WithMany("Items")
                        .HasForeignKey("EquipmentRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_request_items_equipment_requests_equipment_reques");

                    b.Navigation("EquipmentRequest");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.IssueReport", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskAssignment", "TaskAssignment")
                        .WithMany("IssueReports")
                        .HasForeignKey("TaskAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_reports_task_assignments_task_assignment_id");

                    b.Navigation("TaskAssignment");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskHistory", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskAssignment", "TaskAssignment")
                        .WithMany()
                        .HasForeignKey("TaskAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_history_task_assignments_task_assignment_id");

                    b.Navigation("TaskAssignment");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskStepExecution", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskAssignment", "TaskAssignment")
                        .WithMany("TaskStepExecutions")
                        .HasForeignKey("TaskAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_step_executions_task_assignments_task_assignment_id");

                    b.Navigation("TaskAssignment");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskStepExecutionImage", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskStepExecution", "TaskStepExecution")
                        .WithMany("TaskStepExecutionImages")
                        .HasForeignKey("TaskStepExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_step_execution_images_task_step_executions_task_step_e");

                    b.Navigation("TaskStepExecution");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskSwapRequest", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskAssignment", "TargetTaskAssignment")
                        .WithMany("TargetTaskSwapRequests")
                        .HasForeignKey("TargetTaskAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_swap_requests_task_assignments_target_task_assignment_");

                    b.HasOne("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskAssignment", "TaskAssignment")
                        .WithMany("TaskSwapRequests")
                        .HasForeignKey("TaskAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_swap_requests_task_assignments_task_assignment_id");

                    b.Navigation("TargetTaskAssignment");

                    b.Navigation("TaskAssignment");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.EquipmentRequest", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskAssignment", b =>
                {
                    b.Navigation("AdHocRequests");

                    b.Navigation("EmergencyLeaveRequests");

                    b.Navigation("EquipmentRequests");

                    b.Navigation("IssueReports");

                    b.Navigation("TargetTaskSwapRequests");

                    b.Navigation("TaskStepExecutions");

                    b.Navigation("TaskSwapRequests");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskStepExecution", b =>
                {
                    b.Navigation("ComplianceChecks");

                    b.Navigation("TaskStepExecutionImages");
                });
#pragma warning restore 612, 618
        }
    }
}
