// <auto-generated />
using System;
using CleanOpsAi.Modules.TaskOperations.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CleanOpsAi.Modules.TaskOperations.Infrastructure.Migrations
{
    [DbContext(typeof(TaskOperationsDbContext))]
    partial class TaskOperationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.AdHocRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<int>("RequestType")
                        .HasColumnType("integer")
                        .HasColumnName("request_type");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("ReviewedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_assignment_id");

                    b.HasKey("Id")
                        .HasName("pk_adhoc_requests");

                    b.HasIndex("TaskAssignmentId")
                        .HasDatabaseName("ix_adhoc_requests_task_assignment_id");

                    b.ToTable("adhoc_requests", (string)null);
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.ComplianceCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Feedback")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("feedback");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskStepExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_step_execution_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_compliance_checks");

                    b.HasIndex("TaskStepExecutionId")
                        .HasDatabaseName("ix_compliance_checks_task_step_execution_id");

                    b.ToTable("compliance_checks", (string)null);
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.EmergencyLeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("audio_url");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("ReviewedById")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("reviewed_by_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_assignment_id");

                    b.Property<string>("Transcription")
                        .HasColumnType("text")
                        .HasColumnName("transcription");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_emergency_leave_requests");

                    b.HasIndex("TaskAssignmentId")
                        .HasDatabaseName("ix_emergency_leave_requests_task_assignment_id");

                    b.ToTable("emergency_leave_requests", (string)null);
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.EquipmentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("ReviewedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_assignment_id");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_equipment_requests");

                    b.HasIndex("TaskAssignmentId")
                        .HasDatabaseName("ix_equipment_requests_task_assignment_id");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_equipment_requests_worker_id");

                    b.ToTable("equipment_requests", (string)null);
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.IssueReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("ReportedByWorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by_worker_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_assignment_id");

                    b.HasKey("Id")
                        .HasName("pk_issue_reports");

                    b.HasIndex("ReportedByWorkerId")
                        .HasDatabaseName("ix_issue_reports_reported_by_worker_id");

                    b.HasIndex("TaskAssignmentId")
                        .HasDatabaseName("ix_issue_reports_task_assignment_id");

                    b.ToTable("issue_reports", (string)null);
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayLocation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("display_location");

                    b.Property<bool>("IsAdhocTask")
                        .HasColumnType("boolean")
                        .HasColumnName("is_adhoc_task");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("NameAdhocTask")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name_adhoc_task");

                    b.Property<Guid>("OriginalAssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_assignee_id");

                    b.Property<DateTime>("ScheduledStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_start_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_schedule_id");

                    b.HasKey("Id")
                        .HasName("pk_task_assignments");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_task_assignments_assignee_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_task_assignments_status");

                    b.HasIndex("TaskScheduleId")
                        .HasDatabaseName("ix_task_assignments_task_schedule_id");

                    b.ToTable("task_assignments", (string)null);
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_assignment_id");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_task_history");

                    b.HasIndex("TaskAssignmentId")
                        .HasDatabaseName("ix_task_history_task_assignment_id");

                    b.ToTable("task_history", (string)null);
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskStepExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("ResultData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_data");

                    b.Property<Guid>("SopStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("sop_step_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_assignment_id");

                    b.HasKey("Id")
                        .HasName("pk_task_step_executions");

                    b.HasIndex("TaskAssignmentId")
                        .HasDatabaseName("ix_task_step_executions_task_assignment_id");

                    b.ToTable("task_step_executions", (string)null);
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskStepExecutionImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("ImageType")
                        .HasColumnType("integer")
                        .HasColumnName("image_type");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("TaskStepExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_step_execution_id");

                    b.HasKey("Id")
                        .HasName("pk_task_step_execution_images");

                    b.HasIndex("TaskStepExecutionId")
                        .HasDatabaseName("ix_task_step_execution_images_task_step_execution_id");

                    b.ToTable("task_step_execution_images", (string)null);
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskSwapRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("reviewed_by");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("TargetWorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_worker_id");

                    b.Property<Guid>("TaskAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_assignment_id");

                    b.HasKey("Id")
                        .HasName("pk_task_swap_requests");

                    b.HasIndex("TaskAssignmentId")
                        .HasDatabaseName("ix_task_swap_requests_task_assignment_id");

                    b.ToTable("task_swap_requests", (string)null);
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.AdHocRequest", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskAssignment", "TaskAssignment")
                        .WithMany("AdHocRequests")
                        .HasForeignKey("TaskAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_adhoc_requests_task_assignments_task_assignment_id");

                    b.Navigation("TaskAssignment");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.ComplianceCheck", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskStepExecution", "TaskStepExecution")
                        .WithMany("ComplianceChecks")
                        .HasForeignKey("TaskStepExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_compliance_checks_task_step_executions_task_step_execution_");

                    b.Navigation("TaskStepExecution");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.EmergencyLeaveRequest", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskAssignment", "TaskAssignment")
                        .WithMany("EmergencyLeaveRequests")
                        .HasForeignKey("TaskAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_emergency_leave_requests_task_assignments_task_assignment_id");

                    b.Navigation("TaskAssignment");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.EquipmentRequest", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskAssignment", null)
                        .WithMany("EquipmentRequests")
                        .HasForeignKey("TaskAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_requests_task_assignments_task_assignment_id");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.IssueReport", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskAssignment", "TaskAssignment")
                        .WithMany("IssueReports")
                        .HasForeignKey("TaskAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_reports_task_assignments_task_assignment_id");

                    b.Navigation("TaskAssignment");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskHistory", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskAssignment", "TaskAssignment")
                        .WithMany()
                        .HasForeignKey("TaskAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_history_task_assignments_task_assignment_id");

                    b.Navigation("TaskAssignment");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskStepExecution", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskAssignment", "TaskAssignment")
                        .WithMany("TaskStepExecutions")
                        .HasForeignKey("TaskAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_step_executions_task_assignments_task_assignment_id");

                    b.Navigation("TaskAssignment");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskStepExecutionImage", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskStepExecution", "TaskStepExecution")
                        .WithMany("TaskStepExecutionImages")
                        .HasForeignKey("TaskStepExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_step_execution_images_task_step_executions_task_step_e");

                    b.Navigation("TaskStepExecution");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskSwapRequest", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskAssignment", "TaskAssignment")
                        .WithMany("TaskSwapRequests")
                        .HasForeignKey("TaskAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_swap_requests_task_assignments_task_assignment_id");

                    b.Navigation("TaskAssignment");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskAssignment", b =>
                {
                    b.Navigation("AdHocRequests");

                    b.Navigation("EmergencyLeaveRequests");

                    b.Navigation("EquipmentRequests");

                    b.Navigation("IssueReports");

                    b.Navigation("TaskStepExecutions");

                    b.Navigation("TaskSwapRequests");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.TaskOperations.Domain.Entities.TaskStepExecution", b =>
                {
                    b.Navigation("ComplianceChecks");

                    b.Navigation("TaskStepExecutionImages");
                });
#pragma warning restore 612, 618
        }
    }
}
