// <auto-generated />
using System;
using CleanOpsAi.Modules.ServicePlanning.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CleanOpsAi.Modules.ServicePlanning.Infrastructure.Migrations
{
    [DbContext(typeof(ServicePlanningDbContext))]
    [Migration("20260311101243_UpdateFilterSopStep")]
    partial class UpdateFilterSopStep
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CleanOpsAi.Modules.ServicePlanning.Domain.Entities.Sop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("EnvironmentType")
                        .HasColumnType("integer")
                        .HasColumnName("environment_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRequiredCertification")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required_certification");

                    b.Property<bool>("IsRequiredSkill")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required_skill");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("ServiceType")
                        .HasColumnType("integer")
                        .HasColumnName("service_type");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_sops");

                    b.ToTable("sops", (string)null);
                });

            modelBuilder.Entity("CleanOpsAi.Modules.ServicePlanning.Domain.Entities.SopStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigDetail")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_detail");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("SopId")
                        .HasColumnType("uuid")
                        .HasColumnName("sop_id");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_id");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("step_order");

                    b.HasKey("Id")
                        .HasName("pk_sop_steps");

                    b.HasIndex("StepId")
                        .HasDatabaseName("ix_sop_steps_step_id");

                    b.HasIndex("SopId", "StepOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_sop_steps_sop_id_step_order")
                        .HasFilter("is_deleted = false");

                    b.ToTable("sop_steps", (string)null);
                });

            modelBuilder.Entity("CleanOpsAi.Modules.ServicePlanning.Domain.Entities.Step", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action_key");

                    b.Property<string>("ConfigSchema")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_schema");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_steps");

                    b.HasIndex("ActionKey")
                        .IsUnique()
                        .HasDatabaseName("ix_steps_action_key")
                        .HasFilter("is_deleted = false");

                    b.ToTable("steps", (string)null);
                });

            modelBuilder.Entity("CleanOpsAi.Modules.ServicePlanning.Domain.Entities.TaskSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("RecurrenceConfig")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recurrence_config");

                    b.Property<int>("RecurrenceType")
                        .HasColumnType("integer")
                        .HasColumnName("recurrence_type");

                    b.Property<Guid>("SlaShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("sla_shift_id");

                    b.Property<Guid>("SlaTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("sla_task_id");

                    b.Property<Guid>("SopId")
                        .HasColumnType("uuid")
                        .HasColumnName("sop_id");

                    b.Property<Guid?>("WorkAreaDetailId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_area_detail_id");

                    b.HasKey("Id")
                        .HasName("pk_task_schedules");

                    b.HasIndex("SopId")
                        .HasDatabaseName("ix_task_schedules_sop_id");

                    b.ToTable("task_schedules", (string)null);
                });

            modelBuilder.Entity("CleanOpsAi.Modules.ServicePlanning.Domain.Entities.SopStep", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.ServicePlanning.Domain.Entities.Sop", "Sop")
                        .WithMany("SopSteps")
                        .HasForeignKey("SopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sop_steps_sops_sop_id");

                    b.HasOne("CleanOpsAi.Modules.ServicePlanning.Domain.Entities.Step", "Step")
                        .WithMany("SopSteps")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sop_steps_steps_step_id");

                    b.Navigation("Sop");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.ServicePlanning.Domain.Entities.TaskSchedule", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.ServicePlanning.Domain.Entities.Sop", null)
                        .WithMany()
                        .HasForeignKey("SopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_schedules_sops_sop_id");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.ServicePlanning.Domain.Entities.Sop", b =>
                {
                    b.Navigation("SopSteps");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.ServicePlanning.Domain.Entities.Step", b =>
                {
                    b.Navigation("SopSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
