// <auto-generated />
using System;
using CleanOpsAi.Modules.WorkareaCheckin.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CleanOpsAi.Modules.WorkareaCheckin.Infrastructure.Migrations
{
    [DbContext(typeof(WorkareaCheckinDbContext))]
    partial class WorkareaCheckinDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workarea_checkin")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CleanOpsAi.Modules.WorkareaCheckin.Domain.Entities.AccessDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("device_type");

                    b.Property<string>("Identifier")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("identifier");

                    b.Property<string>("InstallationLocation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("installation_location");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkareaCheckinPointId")
                        .HasColumnType("uuid")
                        .HasColumnName("workarea_checkin_point_id");

                    b.HasKey("Id")
                        .HasName("pk_access_devices");

                    b.HasIndex("WorkareaCheckinPointId")
                        .HasDatabaseName("ix_access_devices_workarea_checkin_point_id");

                    b.ToTable("access_devices", "workarea_checkin");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.WorkareaCheckin.Domain.Entities.CheckinRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccessDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_device_id");

                    b.Property<DateTime>("CheckinAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checkin_at");

                    b.Property<string>("CheckinType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("checkin_type");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid?>("TaskStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_step_id");

                    b.Property<Guid>("WorkareaCheckinPointId")
                        .HasColumnType("uuid")
                        .HasColumnName("workarea_checkin_point_id");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_checkin_records");

                    b.HasIndex("AccessDeviceId")
                        .HasDatabaseName("ix_checkin_records_access_device_id");

                    b.HasIndex("CheckinAt")
                        .HasDatabaseName("ix_checkin_records_checkin_at");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_checkin_records_worker_id");

                    b.HasIndex("WorkareaCheckinPointId", "CheckinAt")
                        .HasDatabaseName("ix_checkin_records_workarea_checkin_point_id_checkin_at");

                    b.ToTable("checkin_records", "workarea_checkin");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.WorkareaCheckin.Domain.Entities.WorkareaCheckinPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("WorkareaId")
                        .HasColumnType("uuid")
                        .HasColumnName("workarea_id");

                    b.HasKey("Id")
                        .HasName("pk_workarea_checkin_points");

                    b.HasIndex("WorkareaId", "Code", "IsDeleted")
                        .IsUnique()
                        .HasDatabaseName("ix_workarea_checkin_points_workarea_id_code_is_deleted")
                        .HasFilter("is_deleted = false");

                    b.ToTable("workarea_checkin_points", "workarea_checkin");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.WorkareaCheckin.Domain.Entities.AccessDevice", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.WorkareaCheckin.Domain.Entities.WorkareaCheckinPoint", "WorkareaCheckinPoint")
                        .WithMany("AccessDevices")
                        .HasForeignKey("WorkareaCheckinPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_devices_workarea_checkin_points_workarea_checkin_poi");

                    b.OwnsOne("CleanOpsAi.Modules.WorkareaCheckin.Domain.Owned.BleBeaconInfo", "BleInfo", b1 =>
                        {
                            b1.Property<Guid>("AccessDeviceId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int?>("BatteryLevel")
                                .HasColumnType("integer")
                                .HasColumnName("ble_info_battery_level");

                            b1.Property<DateTime?>("LastMaintenanceAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ble_info_last_maintenance_at");

                            b1.Property<int?>("LastRssi")
                                .HasColumnType("integer")
                                .HasColumnName("ble_info_last_rssi");

                            b1.Property<DateTime?>("LastSeenAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ble_info_last_seen_at");

                            b1.Property<int?>("RssiThreshold")
                                .HasColumnType("integer")
                                .HasColumnName("ble_info_rssi_threshold");

                            b1.Property<string>("ServiceUuid")
                                .HasColumnType("text")
                                .HasColumnName("ble_info_service_uuid");

                            b1.Property<int?>("TxPower")
                                .HasColumnType("integer")
                                .HasColumnName("ble_info_tx_power");

                            b1.HasKey("AccessDeviceId");

                            b1.ToTable("access_devices", "workarea_checkin");

                            b1.WithOwner()
                                .HasForeignKey("AccessDeviceId")
                                .HasConstraintName("fk_access_devices_access_devices_id");
                        });

                    b.Navigation("BleInfo");

                    b.Navigation("WorkareaCheckinPoint");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.WorkareaCheckin.Domain.Entities.CheckinRecord", b =>
                {
                    b.HasOne("CleanOpsAi.Modules.WorkareaCheckin.Domain.Entities.AccessDevice", "AccessDevice")
                        .WithMany()
                        .HasForeignKey("AccessDeviceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_checkin_records_access_devices_access_device_id");

                    b.HasOne("CleanOpsAi.Modules.WorkareaCheckin.Domain.Entities.WorkareaCheckinPoint", "WorkareaCheckinPoint")
                        .WithMany("CheckinRecords")
                        .HasForeignKey("WorkareaCheckinPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_checkin_records_workarea_checkin_points_workarea_checkin_po");

                    b.Navigation("AccessDevice");

                    b.Navigation("WorkareaCheckinPoint");
                });

            modelBuilder.Entity("CleanOpsAi.Modules.WorkareaCheckin.Domain.Entities.WorkareaCheckinPoint", b =>
                {
                    b.Navigation("AccessDevices");

                    b.Navigation("CheckinRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
